### ISSUE TITLE
Common ancestor for Sun and Moon

### ISSUE THREAD

**Issue by BlackBird-One** [Sunlitt/SunKit#10]
It would be practical if Sun and Moon had a common ancestor that had properties that both classes have the same (date, altitude, rise, set ....). 

Right now I have two almost identical methods, although one would be enough.

Thanks, Michal Kůs

**Comment by davideilmito** [comment]
Hi Michal, we are aware that could be better to have a common ancestor for both Sun and Moon class, they also share the same codebase, but keep them separated is an our choice.  For now they will kept separated, in the future we will consider to join them.
Thanks :)
