### ISSUE TITLE
SunKit in a view in Xcode

### ISSUE THREAD

**Issue by seeshabu** [Sunlitt/SunKit#2]
Hello,

I have downloaded SunKit and installed in via the Swift Package Manager in Xcode.

I want to show in a view (example the ContentView) for example the sunrise time.

Is it possible to provide me the code to do this. As I am relatively new to SwiftUI (You have to start somewhere I guess), I am a little bit lost 'in the moment' :)  

Is it possible to help me and show me how I can show these time in a Xcode View?

Your help would be appreciated.

**Comment by seldon1000** [comment]
Hello there!

I am sorry for the late response.

I am happy you are interested in using SunKit and I am glad to help you with that.

SunKit provides the sunrise time in its member `sunrise` which is of Swift type `Date`. To correctly show it in a SwiftUI view, you can use this simple code below:

```swift
import SwiftUI
import SunKit

struct SwiftUIView: View {
    let sun: Sun = Sun.common
    let timeFormatter: DateFormatter = {
        let tf = DateFormatter()
        tf.dateFormat = "HH:mm"
        
        return tf
    }()
    
    var body: some View {
        VStack {
            Text("Azimuth: \(sun.azimuth)°")
            Text("Elevation: \(sun.elevation.degrees)°")
            Text("Sunrise time: \(timeFormatter.string(from: sun.sunrise))")
        }
    }
}

struct SwiftUIView_Previews: PreviewProvider {
    static var previews: some View {
        SwiftUIView()
    }
}
```

We use an instance of Sun which by default is localized in Cupertino, California, to get all the data related to the Sun. Then, we use a `DateFormatter` instance to format the sunrise time making it understandable to humans 😃.

I am available if you need anything else!

**Comment by seeshabu** [comment]
Many thanks for your help. Much appreciated. 
I am struggling to modify your code so that the user will get the sunrise  time of the location he or she is (via CoreLocation).
Is it possible to give a helping hand for this issue ?

**Comment by seldon1000** [comment]
I am gonna have to point you to Apple's documentation (https://developer.apple.com/documentation/corelocation).

Keep in mind that the class Sun in SunKit provides two methods: `setLocation()` and `setTimeZone()`. Use this two to set the location and timezone taken from CoreLocation and get updated data.

**Comment by seeshabu** [comment]
I think I am close, but it still returns a Unknown location and an unknown timezone.

`
import SwiftUI
import SunKit
import CoreLocation

class LocationManagerDelegate: NSObject, CLLocationManagerDelegate {
    var contentView: ContentView?
    var locationManager = CLLocationManager()
    func locationManager(_ manager: CLLocationManager, didUpdateLocations locations: [CLLocation]) {
        guard let location = locations.last else { return }
        if let contentView = contentView {
            do {
                try contentView.sun.setLocation(location)
                contentView.location = location
            } catch let error {
                print(error)
            }
        }
        let geocoder = CLGeocoder()
        geocoder.reverseGeocodeLocation(location) { (placemarks, error) in
            if let error = error {
                print(error)
                return
            }
            if let placemarks = placemarks, let placemark = placemarks.first, let timeZone = placemark.timeZone {
                if let contentView = self.contentView {
                    contentView.timeZone = timeZone
                    print("TimeZone: \(timeZone.identifier) offset : \(timeZone.secondsFromGMT())")
                    do { try contentView.sun.setTimeZone(Double(timeZone.secondsFromGMT()) / 3600.0)
                    } catch let error {
                        print(error)
                    }
                }
            }
        }
    }

    func locationManager(_ manager: CLLocationManager, didChangeAuthorization status: CLAuthorizationStatus) {
          if status == .authorizedWhenInUse {
              locationManager.startUpdatingLocation()
          }
      }
  }
       
struct ContentView: View {
    let sun: Sun = Sun.common
    let timeFormatter: DateFormatter = {
        let tf = DateFormatter()
        tf.dateFormat = "HH:mm"
        return tf
    }()
    @State var locationManager = CLLocationManager()
    @State var locationManagerDelegate = LocationManagerDelegate()

    @State public var location: CLLocation?
    @State public var timeZone: TimeZone?

    init() {
        locationManagerDelegate.contentView = self
        locationManager.delegate = locationManagerDelegate
        locationManager.desiredAccuracy = kCLLocationAccuracyBest
        locationManager.requestWhenInUseAuthorization()
    }
    
        
    var body: some View {
        VStack {
            Text("Azimuth: \(sun.azimuth)°")
            Text("Elevation: \(sun.elevation.degrees)°")
            Text("Sunrise time: \(timeFormatter.string(from: sun.sunrise))")
            if let location = location {
                Text("Current Location: \(location.coordinate.latitude), \(location.coordinate.longitude)")
            } else {
                Text("Current Location: Unknown")
            }
            if let timeZone = timeZone {
                Text("Time Zone: \(timeZone.abbreviation() ?? "Unknown")")
            } else {
                Text("Time Zone: Unknown")
            }
        }
    }
}





    struct ContentView_Previews: PreviewProvider {
        static var previews: some View {
            ContentView()
        }
    }
`

**Comment by seldon1000** [comment]
You are injecting your contentview inside your location manager class. This is wrong.
Try moving your location and timezone variables inside the manager class, so that you don't have to inject the whole contentview. However this is not an issue related to SunKit anymore, so I have to close it.

If you have any other question related to SunKit, you free to open a new issue.
