### ISSUE TITLE
Sun azimuth at current time

### ISSUE THREAD

**Issue by E-Lizzy** [Sunlitt/SunKit#43]
Hello,

thank you for your awesome work.

As the sun moves from sunrise to sunset in a given location you provide the azimuth of the sun on sunrise and sunset.
I have a question: is it possible to have the data of the current position of the sun. For example if it is 10h30 to see the position of the sun on the map between sunrise and sunset, and if the time evolves you see the sun on a map moving?

is this possible?

**Comment by seldon1000** [comment]
Hello there! We are glad that you like SunKit.

Current sun data is already present in your Sun object. For instance, you can check the current sun azimuth by simply accessing Sun's `azimuth` parameter. You can set the desired time of the day using `setDate(_ newDate: Date)` and azimuth will be updated to match the newly set date.

I hope I helped you.

**Comment by E-Lizzy** [comment]
how do you convert sun.azimuth to the current time? It is not clear to me

**Comment by seldon1000** [comment]
You first set the time using the `setDate` method. The method will then update the azimuth value automatically.

**Comment by E-Lizzy** [comment]
Is it possible to provide an example ? It would be appreciated

**Comment by seldon1000** [comment]
Oh course, you can find it in the README file.

**Comment by E-Lizzy** [comment]
Thank you very much for your help. I succeeded :-)

**Comment by seldon1000** [comment]
You're welcome!
