### ISSUE TITLE
Sunset  time tomorrow

### ISSUE THREAD

**Issue by E-Lizzy** [Sunlitt/SunKit#44]
Hello I am a little bit confused.
I want to see the sunset time of tomorrow. I am a little bit stuck with the date.
How can I modify tthe code to retrieve the sunset time of tomorrow?

**Comment by seldon1000** [comment]
Hello. To retrieve tomorrow's sunset time you need to use the `setDate` method to set the date to tomorrow. Then, the method automatically updates the sun events times in your `sun` instance.

I redirect you to Apple's documentation for Calendar and DateComponents:
https://developer.apple.com/documentation/foundation/calendar
https://developer.apple.com/documentation/foundation/datecomponents
