### ISSUE TITLE
Working with the time zone

### ISSUE THREAD

**Issue by BlackBird-One** [Sunlitt/SunKit#9]
Hey, 
I used SunKit and MoonKit in my upcoming application. I like them and it's great that the classes are still alive and that you keep improving them.

In practical implementation, I've encountered difficulties when working with time zones and would have a tip for an improvement that would greatly simplify their use. 

My difficulties:
When I want to use a Sun class for a time zone other than the current time zone, I have to work very carefully with the time zone. 
For example: the facility is located in Prague and I need the position of the sun during the day in Cupertino. 
- Before initializing, I need to calculate the time zone offset in Cupertino and pass it to the Sun class as a Double
- pre-shift each date set via setDate() to the Cupertino time zone 
- in addition, I have to recalculate and set setTimeZone() before setDate() because the previous date could have a different DST

This is not a safe and convenient solution.

That's why I propose to initialize the Sun class with the TimeZone class. 
The Sun class can then do all the necessary conversions for time zones by itself:
- calculate the time zone offset itself
- adjust the time passed via setDate by itself
- calculate the DST itself

Michal Kus

**Comment by davideilmito** [comment]
Hi Michal, thanks to have starred both SunKit and MoonKIt.

Please be aware that the date you are setting with `setDate` method is timezone agnostic.
It's more easy for me to explain it with an example:

```swift
let naplesLocation: CLLocation = .init(latitude: 40.84014, longitude: 14.25226)
let timeZoneNaples: Double = 1
      
//Step1: Creating Sun instance in Naples and with timezone +1
var sunUnderTest = Sun.init(location: naplesLocation, timeZone: timeZoneNaples)
        
//Step2: Setting current date 11/03/23 10:22 as date.
var dateUnderTest = Date()
sunUnderTest.setDate(dateUnderTest)

let tokyoLocation: CLLocation = .init(latitude: 35.68946, longitude: 139.69172)
let timeZoneTokyo: Double = 9

sunUnderTest.setLocation(tokyoLocation)
sunUnderTest.setTimeZone(timeZoneTokyo)

sunUnderTest.azimuth   //This is the azimuth of the Sun in Tokyo at 11/03/23 10:22 local time in Tokyo,no conversion is needed

```

Said that, I get your point, and I will work to improve SunKit and the way It handles timezones and location changes on the branch related to this issue.
The issue will stay open until the changes are on master.

**Comment by BlackBird-One** [comment]
Thank you, and I will look forward to the edit. 
Even in its current state, your libraries are good and usable. Unfortunately the current work with the Date class is not correct. It is easy to make mistakes because of it.

**Comment by davideilmito** [comment]
Hi Michal, 
here you can find more on what has been done: [Link](https://github.com/Sunlitt/SunKit/pull/11).

**Comment by BlackBird-One** [comment]
Thank you for your lightning response.
